### ISSUE TITLE
json schema for create_shipping_label in shipment_request is wrong

### ISSUE THREAD

**Issue by PhilReinking** [shipcloud/shipcloud.github.io#26]
Your JSON schema says that the `create_shipping_label`field accepts a boolean value.

It turned out that this boolean value has to be enclosed by quotation marks to get it to work, which in my mind is not correct. There should be a hint on that issue.

Also the Shipcloud API should accept real boolean values to make things easier.

**Comment by acwebionate** [comment]
Hey @PhilReinking we're allowing both (boolean and string value), because of legacy reasons, but would love to receive boolean. Could you send us the request you were trying to send at developers@shipcloud.io so we can have a look?
