### ISSUE TITLE
API reference is missing the 401 status code

### ISSUE THREAD

**Issue by akomm** [shipcloud/shipcloud.github.io#99]
Documentation does not contain the 401 code. When I send a request without an API key, I get 401.
If you use 401 for "unauthenticated" and 403 for "unauthorized", then, additionally the description of status code 403 is incorrect, as it states the code being returned for both "unauthenticated" and "unauthorized".

**Comment by andrecedik** [comment]
Hi @akomm,
thanks for pointing that out. I'll add this asap.

**Comment by andrecedik** [comment]
Resolved this via commit https://github.com/shipcloud/shipcloud.github.io/commit/400b16494b3b82e2b8bd7e3211266c8b54285200
